[package]
name = "event-listener"
version = "0.1.0"
edition = "2021"

[dependencies]
db = { path = "../db" }
sqlx = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
dotenvy = {workspace = true}
solana-client = {workspace = true}

solana-sdk = {workspace = true}
solana-commitment-config = "3.1.0"
tokio-stream = "0.1.17"
solana-account-decoder = "3.0.10"
anchor-lang = {workspace = true}

solana-program = "3.0.0"
base64 = "0.22.1"
