[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
db = { path = "../db" }
anyhow = { workspace = true }
dotenvy = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
rust_decimal = { workspace = true }
axum = "0.8.6"
privy-rs = "0.1.0-alpha.4"
jsonwebtoken = { version = "10.2.0", features = ["rust_crypto"] }
matching-engine = { path = "../matching-engine" }
